version: "3.9"

services:
  db:
    image: postgres
    env_file:
      - ./.env

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - SQL_HOST=db